### ISSUE TITLE
Feature suggestion - Link to issue on GitHub, instead of local phpBB ticket field

### ISSUE THREAD

**Issue by Dode123** [phpbb/ideas#110]
![Annotation 2020-05-02 201626](https://user-images.githubusercontent.com/31342092/80872381-d17dbd00-8cb1-11ea-9671-4b7ccb09b98f.jpg)
Would it be possible to add an option for us to swap out the local phpBB ticket field, with a field that can be linked to GitHub issue? Should be pretty small of a change?

**Comment by VSEphpbb** [comment]
Don't see the need. Every thing that ends up on GitHub for phpBB begins as a ticket. That is, there will always be tickets, before there ever is, if ever, a github PR. So the ticket is more logical choice as well as the fact that if there is a PR on Github, there's already a link to it from the ticket.

**Comment by Dode123** [comment]
Sure ok. But maybe you could give me a few pointers, I'd imagine this would be quick to edit? What files would I need to edit? 
Ideas.js and idea_body.html?

**Comment by DavidIQ** [comment]
It doesn't look like the ticket field is able to be used outside of phpbb.com.

**Comment by Dode123** [comment]
Can't I just change the limitation in ideas.js that limits only URLs from phpbb dev tracker?

**Comment by DavidIQ** [comment]
For now, it looks like you would need to edit these two lines:
https://github.com/phpbb/ideas/blob/master/styles/prosilver/template/ideas.js#L218
https://github.com/phpbb/ideas/blob/master/styles/prosilver/template/idea_body.html#L70

The field will only accept numbers, but I think that's fine for GitHub tickets.

**Comment by Dode123** [comment]
yes I already tried altering those lines, but didn't work. Still get error when entering just the issue number. (576, which is this one: https://github.com/Longwelwind/swords-and-ravens/issues/576) 

I changed to 
`.attr('href', 'https://github.com/Longwelwind/swords-and-ravens/issues/' + value);`
and
`<a id="ticketlink" class="ideamodbtn" {% if IDEA_TICKET %}href="https://github.com/Longwelwind/swords-and-ravens/issues{{ IDEA_TICKET }}">Github-{{ IDEA_TICKET }}{% else %}style="display:none">{% endif %}</a>`

**Comment by DavidIQ** [comment]
Did you purge the cache from the ACP? And what error are you getting?

**Comment by Dode123** [comment]
Yes, I always purge =) 

This error:
![Annotation 2020-05-05 204552](https://user-images.githubusercontent.com/31342092/81103517-6cc09d80-8f11-11ea-8688-bc3c2afb8ff5.jpg)

**Comment by Dode123** [comment]
This snippet in ideas.js possibly? 

`			
if (value && !(info = /^PHPBB3-(\d{1,6})$/.exec(value))) {
				phpbb.alert($this.attr('data-l-err'), $this.attr('data-l-msg'));
				return;
			}
			if (value) {
				value = 'PHPBB3-' + info[1]; `

**Comment by DavidIQ** [comment]
Ah of course there's client-side validation...
https://github.com/phpbb/ideas/blob/master/styles/prosilver/template/ideas.js#L206

You'll need to change those lines to:
```
if (value && !(info = /^\d{1,}$/.exec(value))) {
	phpbb.alert($this.attr('data-l-err'), $this.attr('data-l-msg'));
	return;
}			
```
You'll want to remove this altogether:
```
if (value) {
	value = 'PHPBB3-' + info[1];
}
```

**Comment by DavidIQ** [comment]
You'll probably want to change the error text as well to something more appropriate:
https://github.com/phpbb/ideas/blob/master/language/en/common.php#L80

**Comment by Dode123** [comment]
Yeah changed both of those =) I can save the link properly now. =)

Now the only problem is, that when I reload, the number is removed.. haha why is it doing that? Does it do that in the regular ideas extension vs the phpbb dev tracker? 

I enter number, it saves successfully, I can see and click the link, it works. Then I refresh, and it's gone. Now I just get the "add" button again.

**Comment by DavidIQ** [comment]
https://github.com/phpbb/ideas/blob/master/styles/prosilver/template/ideas.js#L215
Change that to:
```
$.get(url, {ticket: value}, function(res) {
```

**Comment by Dode123** [comment]
Yeah, that didn't work. Still doesn't save on refresh. 

Something in that segment... hmm. 
And just to rule out any typos, here is the segment in my file: 
![Annotation 2020-05-05 211147](https://user-images.githubusercontent.com/31342092/81105945-0b9ac900-8f15-11ea-86dd-078e907fbb4b.jpg)

**Comment by DavidIQ** [comment]
If that is your current script you still have `&& info[1]` there.

**Comment by Dode123** [comment]
Yeah I noticed as soon as I posted! 

It works now =) 
https://community.swordsandravens.net/viewtopic.php?f=17&t=3 

Thank you for all the help!

**Comment by Dode123** [comment]
Also, for future reference, if anyone else is looking to change that field (as it won't have any use for anyone downloading this extension for use on their site), this would show what they would need to change to make it for for their own tracker/Git etc.

+ Will the issue extension ever be added to the official extension database? Or won't this be changed upon in any form?

**Comment by DavidIQ** [comment]
I guess you probably meant Idea extension.

I don't know if we gave the impression that this is being abandoned, but it's not, especially since we're actively using it on phpbb.com. However officially publishing it in the CDB is not really something we're planning to do, at least not yet, since adding official extensions to the CDB carries the overhead of support.

**Comment by Dode123** [comment]
> I guess you probably meant Ideas extension.
> 
> I don't know if we gave the impression that this is being abandoned, but it's not, especially since we're actively using it on phpbb.com. However officially publishing it in the CDB is not really something we're planning to do, at least not yet, since adding official extensions to the CDB carries the overhead of support.

Aah okay. Good to hear that it will still be updated when needed =) Yeah I can understand that, thanks for the info.

**Comment by Dode123** [comment]
Hi again @DavidIQ 
Would you know what edits I would need to do to ideas.js to enable me to link ideas to git issue numbers again? I see after I did updates to phpBB and ideas, that of course my custom edits does no longer work, as it seems like there has been some code changes. The above references you posted back in 2020, doesn't appear to work anymore. =)
