### ISSUE TITLE
Replace thumbs up/down green/red images with CSS

### ISSUE THREAD

**Issue by DavidIQ** [phpbb/ideas#112]
Right now it's an image being used as a background. It's already a div so it can be properly styled through a CSS class. Can use these from Font Awesome for the thumbs:

https://fontawesome.com/v4.7.0/icon/thumbs-o-up
https://fontawesome.com/v4.7.0/icon/thumbs-o-down

**Comment by hanakin** [comment]
Consider using something more future proof maybe if you are not already using font-awesome I would suggest iconify makes it easy to use any font from any library while providing svg versions of the icons?

**Comment by VSEphpbb** [comment]
Font awesome is already baked into phpBB. The future where it will be gone is far enough away that it can be dealt with later on at that time.

**Comment by VSEphpbb** [comment]
Some ideas for marking that you already voted on a rating on the idea index can be found here:

https://codepen.io/matt_codez/pen/ZEbryNe

**Comment by DavidIQ** [comment]
I'm leaning towards the last one.
