### ISSUE TITLE
Move to online platform for translation

### ISSUE THREAD

**Issue by pYFZOS5** [phpbb/ideas#141]
I thought to start to work for new language (for entire thing) but it's quite difficult for few persons to do at free time while contribute to other projects and you've strict condition for packs https://github.com/phpbb/phpbb-translation-policies/blob/3.2.x/guidelines.md

It's not impossible to follow current translation procedure but it also has many cons for both phpbb and especially translators side and this affect to less popular languages too.

You have mentioned below details on this guide https://www.phpbb.com/language/apply/
_"That's why most of our current translators use a distributed revision control system to manage translations. We recommend to use Git as software and GitHub as host because we use them for our projects, so it will be easier for you to fork them and send us your translations."_

So i suggest to use online platform for translation.
Weblate - opensource libre project (phpbb also opensource) https://weblate.org/en/download/
cloud service free for libre projects https://hosted.weblate.org/hosting/ or you can host it yourself. furthermore you can set selected users to save translation directly for each languages and rest contributors able to suggest. It use by many projects such as matrix, opensuse, fedora, mattermost
Crowdin - propitary service (has free plan https://crowdin.com/pricing#annual) it has options to configure basic translators, proofreaders features if necessary

**Comment by DavidIQ** [comment]
Thank you for the suggestions, but none of that has anything to do with this extension. If you have a suggestion for phpBB then the proper location for that is at https://www.phpbb.com/community/ideas
