### ISSUE TITLE
Bug - Ideas are not sorted by top

### ISSUE THREAD

**Issue by Nicofuma** [phpbb/ideas#71]
Look at https://www.phpbb.com/community/ideas/list/top?sd=d&start=45
The ideas do not seem to be sorted by top

**Comment by VSEphpbb** [comment]
There is some crazy forumla Callum found for sorting ideas. So the one's with downvotes seemt o take more of a hit thn those with no downvotes.

**Comment by VSEphpbb** [comment]
See https://github.com/phpbb/ideas/blob/master/factory/ideas.php#L185-L196

**Comment by VSEphpbb** [comment]
This looks good to me:
https://www.phpbb.com/community/ideas/list/top
@Nicofuma your link is from page 4.
I don't really see an issue here, considering the weighting forumla is what sorts them, even though at glance it may look weird if you just look at the number of votes

**Comment by DavidIQ** [comment]
While we're looking at this would it be possible to cache this query if we aren't already? Looks a bit heavy.

**Comment by VSEphpbb** [comment]
I don't know because it has some variables in it that can make it different, i.e.: sort direction

**Comment by Nicofuma** [comment]
Honestly I don't like the weighted formula; I think it gives to much power to downvotes.
Per example, this idea https://www.phpbb.com/community/idea/76 should definitely be displayed before this one https://www.phpbb.com/community/idea/214 but it is actually page 5 while the second one is page 2.

I find it weird to find ideas with more than 20 up votes (2/3 of all votes) page 5

**Comment by Elsensee** [comment]
@Nicofuma I agree but it's also not a good solution to just sort by upvotes first because then ideas which are longer in the database can easily stay on top of the list forever.

**Comment by VSEphpbb** [comment]
For what it's worth, this is the sorting query Ideas has always used. But at any rate, it attempts to give votes that really are the most popular at the top. Down votes start making an idea unpopular. So an idea with 5+ and 0- is going to be more popular than one with 100+ and 95-

The article linked to with the query code does a good job of explaining why this is a useful algorithm for sorting up/down votes.

**Comment by marc1706** [comment]
Yes, I think it's better to keep the current formula. That's why we suggested to show a random idea to make even ones on the back pages more popular and more often looked at.
