### ISSUE TITLE
Open topic in last unread message

### ISSUE THREAD

**Issue by DavidIQ** [phpbb/ideas#77]
Currently when one clicks on an idea the user is taken to the first post. It would be preferable to be put into the last unread. Should be as simple as opening the topic with `&view=unread#unread` added to the URL to get the desired effect.

**Comment by Elsensee** [comment]
Not always IMHO. I would do it just like in the forums where you can click on the icon or something similar.

**Comment by VSEphpbb** [comment]
Currently it should behave exactly as forums, since it is basically still just a forum. Click the red topic icon to go to unread, click the title to go to the top of topic (where all the idea stats are).

**Comment by DavidIQ** [comment]
Then we need a link to the latest post for the idea somewhere in the list.

**Comment by VSEphpbb** [comment]
Ah, you are right. That is a bug.
