### ISSUE TITLE
 just wondering when this could be used for production forums?

### ISSUE THREAD

**Issue by raykai** [phpbb/ideas#84]
Hi, just wondering when this could be used for production forums?

would really like to have this on my forum, but readme says " This extension is currently under development and is not recommended for use on any live forum" ... but its live on phpBB so does this mean it's ready for live forum use?

**Comment by DavidIQ** [comment]
Sure, go right ahead. No support will be provided however and there are currently no plans to add this to the Customisations Database.

**Comment by raykai** [comment]
Oh why would you not add this to the extension list over at PhpBB ?
