### ISSUE TITLE
First post of a thread should be editable like the following ones

### ISSUE THREAD

**Issue by jidanni** [phpbb/ideas#87]
It would be great if the first post of a thread could be editable like the following ones.
https://www.phpbb.com/community/viewtopic.php?p=14862151
Currently if one accidentally pastes his Social Security Number into the first post due to some browser bug, he cannot edit it nor delete it.

**Comment by jidanni** [comment]
If the same editor was used for the first post, second posts just to attach images,
https://www.phpbb.com/community/viewtopic.php?f=436&t=2234006#p13585906
could be avoided too.

**Comment by jidanni** [comment]
Also users very much want to make sure their Idea looks good. Alas there is no Preview button. So they would go to some unrelated thread and practice using the Preview button there... possibly at the very end forgetting where they were and clicking Submit!...

**Comment by DavidIQ** [comment]
Hello,

Please create separate issues for each one of those things. Making this a catch-all of these issues you've reported is not very useful especially if different people will take on different parts of issues.

**Comment by jidanni** [comment]
Thank you @DavidIQ but there really is just one issue: Replacing the
```
Submit
```
button with
```
￼Save draft  ￼Preview  ￼Submit 
```
on the first post of an Ideas thread.

**Comment by DavidIQ** [comment]
Your first 2 messages in this issue are not related to the initial report. Adding `Save draft` and `Preview` buttons would not give the user the ability to edit their idea.

**Comment by jidanni** [comment]
Oh. I see.
My experience was that whenever there were those three buttons at the
bottom of the form, after submitting, there would also be a pencil icon
available to go back and edit.

So I am rather sure they are both part of the same component so maybe
not opening separate reports would be even better.

**Comment by DavidIQ** [comment]
As one of the developers involved in creating this extension I can tell you that they're not and are not things that would happen on the same page even... not really sure why I need to mention to you a 3rd time that these need to be separate issues. At this point please create 3 new issues including the original one reported here as this one will be closed.

Thanks.
