### ISSUE TITLE
Allow editing of the first post of an ideas thread

### ISSUE THREAD

**Issue by jidanni** [phpbb/ideas#89]
Please allow going back and editing of the first post of an ideas thread,
just like its replies have. (Pencil Icon).
See #87.

**Comment by VSEphpbb** [comment]
Editing the first post is not allowed for a reason. People are voting on the idea that was presented. We do not want a situation where the OP comes in and changes their idea after voting has been underway. If the OP has things to add, amend or discuss about their idea, it should be done in the discussion instead.
