### ISSUE TITLE
phpbb Ideas forum: see own votes in topic list

### ISSUE THREAD

**Issue by warmweer** [phpbb/ideas#90]
Currently in phpBB Ideas forum, the number of YES and NO votes can be seen in the topic list, but no one's own vote. It would help seeing whether the user had voted already (and how he voted) to avoid having to click in each topic to see whether a vote had been cast or not.
In my case, there are over 100 topics which I haven't read yet (or have not yet decided on whether to vote or on how to vote). Similarly there are topics where I have changed my vote (I think) but I have to click in order to see whether I have effectively changed or removed my vote.

Adding a coloured star to the topic icon (or a dot to the YES or NO button) could allow a quick oversight of one's own votes and also prevent a lot of unnecessary clicks.

Also (not really an issue), including a third voting option (NEUTRAL) could give more insight into how many people were actually interested enough in the idea and have no arguments for, nor against the idea being implemented.

**Comment by Dode123** [comment]
Could this be added? =)

**Comment by DavidIQ** [comment]
The way GitHub does it in the case of liking a comment is by changing the shading of the area where the "thumbsup" icon shows. These are just some ideas for how we can show a sort of inconspicuous indicator on the list:
![image](https://user-images.githubusercontent.com/186341/81107272-e55d3500-8ee4-11ea-8086-0278e1d6b3fe.png)

Could also show a dot I suppose.

**Comment by Dode123** [comment]
Yeah either showing a dot or the V/X icon is a good way of doing it :)

**Comment by VSEphpbb** [comment]
I don't like the check or X because they push the numbers. Opens the possibility of problems with large numbers getting pushed into the icons.

**Comment by DavidIQ** [comment]
Agreed. We should also consider ditching those boxes as images and use a purely CSS solution for showing them. Would make controlling the color for the text and hand easier/possible and we could just go down that path for showing an indicator.
